COPTS = -g
SRC=fly.c objects.c gltext.c spin.c scene.c display.c input.c reshape.c compass.c ppm.c gettime.c midi.c
OBJS=${SRC:.c=.o}
HEADERS=gltext.h display.h spin.h objects.h input.h reshape.h point.h freeze.h compass.h ppm.h gettime.h midi.h
INCS=-I/usr/local/include -I/usr/disney/users1/pbranna/include
LIBS=-L/usr/disney/users1/vernon/pub/lib -L/usr/lib32/internal -lglut -lGLU -lGL -lm -L/usr/X11/lib -lX11 -lXi -lXt -lXmu
OUT=fly
CFLAGS = -O2 -mips4 -DSGI


##### RULES #####

.SUFFIXES: .c .o .ln

.c.o: 
	${CC} ${INCS} ${CFLAGS} -c ${INCDIR} $< -o $@

default: dep sim

sim: ${OBJS}
	${CC} ${CFLAGS} -o ${OUT} ${OBJS} ${LIBS}

dep:
	makedepend -I/usr/include $(INCS) ${SRC}

clean: ${HEADERS}
	/bin/rm -f ${OBJS} ${OUT}

########################################################################
# DO NOT DELETE THIS LINE

fly.o: /usr/include/stdio.h /usr/include/features.h
fly.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
fly.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
fly.o: /usr/include/gnu/stubs-32.h /usr/include/bits/types.h
fly.o: /usr/include/bits/typesizes.h /usr/include/libio.h
fly.o: /usr/include/_G_config.h /usr/include/wchar.h
fly.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
fly.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
fly.o: /usr/include/endian.h /usr/include/bits/endian.h
fly.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
fly.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
fly.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
fly.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
fly.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
fly.o: /usr/include/GL/gl.h /usr/include/GL/glext.h /usr/include/inttypes.h
fly.o: /usr/include/stdint.h /usr/include/bits/wchar.h /usr/include/GL/glu.h
fly.o: /usr/include/assert.h scene.h gltext.h spin.h display.h input.h
fly.o: reshape.h freeze.h compass.h gettime.h midi.h
objects.o: /usr/include/assert.h /usr/include/features.h
objects.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
objects.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
objects.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
objects.o: /usr/include/sys/types.h /usr/include/bits/types.h
objects.o: /usr/include/bits/typesizes.h /usr/include/time.h
objects.o: /usr/include/endian.h /usr/include/bits/endian.h
objects.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
objects.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
objects.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
objects.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
objects.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
objects.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
objects.o: /usr/include/inttypes.h /usr/include/stdint.h
objects.o: /usr/include/bits/wchar.h /usr/include/GL/glu.h
objects.o: /usr/include/math.h /usr/include/bits/huge_val.h
objects.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
objects.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
objects.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
objects.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
objects.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
objects.o: /usr/include/bits/sys_errlist.h objects.h reshape.h input.h ppm.h
objects.o: point.h
gltext.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
gltext.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
gltext.o: /usr/include/inttypes.h /usr/include/features.h
gltext.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
gltext.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
gltext.o: /usr/include/gnu/stubs-32.h /usr/include/stdint.h
gltext.o: /usr/include/bits/wchar.h /usr/include/GL/glu.h
gltext.o: /usr/include/stdlib.h /usr/include/sys/types.h
gltext.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
gltext.o: /usr/include/time.h /usr/include/endian.h
gltext.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
gltext.o: /usr/include/sys/select.h /usr/include/bits/select.h
gltext.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
gltext.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
gltext.o: /usr/include/alloca.h gltext.h
spin.o: /usr/include/sys/time.h /usr/include/features.h
spin.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
spin.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
spin.o: /usr/include/gnu/stubs-32.h /usr/include/bits/types.h
spin.o: /usr/include/bits/typesizes.h /usr/include/time.h
spin.o: /usr/include/bits/time.h /usr/include/sys/select.h
spin.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
spin.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
spin.o: /usr/include/bits/confname.h /usr/include/getopt.h
spin.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
spin.o: /usr/include/GL/gl.h /usr/include/GL/glext.h /usr/include/inttypes.h
spin.o: /usr/include/stdint.h /usr/include/bits/wchar.h /usr/include/GL/glu.h
spin.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/endian.h
spin.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
spin.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
spin.o: /usr/include/alloca.h spin.h gettime.h
scene.o: /usr/include/math.h /usr/include/features.h
scene.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
scene.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
scene.o: /usr/include/gnu/stubs-32.h /usr/include/bits/huge_val.h
scene.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
scene.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
scene.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
scene.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
scene.o: /usr/include/GL/gl.h /usr/include/GL/glext.h /usr/include/inttypes.h
scene.o: /usr/include/stdint.h /usr/include/bits/wchar.h
scene.o: /usr/include/GL/glu.h /usr/include/stdlib.h /usr/include/sys/types.h
scene.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
scene.o: /usr/include/time.h /usr/include/endian.h /usr/include/bits/endian.h
scene.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
scene.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
scene.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
scene.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h objects.h
scene.o: reshape.h scene.h spin.h input.h
display.o: /usr/include/math.h /usr/include/features.h
display.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
display.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
display.o: /usr/include/gnu/stubs-32.h /usr/include/bits/huge_val.h
display.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
display.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
display.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
display.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
display.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
display.o: /usr/include/inttypes.h /usr/include/stdint.h
display.o: /usr/include/bits/wchar.h /usr/include/GL/glu.h
display.o: /usr/include/stdlib.h /usr/include/sys/types.h
display.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
display.o: /usr/include/time.h /usr/include/endian.h
display.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
display.o: /usr/include/sys/select.h /usr/include/bits/select.h
display.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
display.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
display.o: /usr/include/alloca.h display.h fsim.h
input.o: /usr/include/ctype.h /usr/include/features.h
input.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
input.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
input.o: /usr/include/gnu/stubs-32.h /usr/include/bits/types.h
input.o: /usr/include/bits/typesizes.h /usr/include/endian.h
input.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
input.o: /usr/include/xlocale.h /usr/include/GL/glut.h
input.o: /usr/include/GL/freeglut_std.h /usr/include/GL/gl.h
input.o: /usr/include/GL/glext.h /usr/include/inttypes.h
input.o: /usr/include/stdint.h /usr/include/bits/wchar.h
input.o: /usr/include/GL/glu.h /usr/include/stdlib.h /usr/include/sys/types.h
input.o: /usr/include/time.h /usr/include/sys/select.h
input.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
input.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
input.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
input.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
input.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
input.o: /usr/include/bits/sys_errlist.h /usr/include/assert.h
input.o: /usr/include/math.h /usr/include/bits/huge_val.h
input.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
input.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
input.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h spin.h
input.o: reshape.h freeze.h input.h fsim.h gettime.h compass.h
reshape.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
reshape.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
reshape.o: /usr/include/inttypes.h /usr/include/features.h
reshape.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
reshape.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
reshape.o: /usr/include/gnu/stubs-32.h /usr/include/stdint.h
reshape.o: /usr/include/bits/wchar.h /usr/include/GL/glu.h
reshape.o: /usr/include/stdlib.h /usr/include/sys/types.h
reshape.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
reshape.o: /usr/include/time.h /usr/include/endian.h
reshape.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
reshape.o: /usr/include/sys/select.h /usr/include/bits/select.h
reshape.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
reshape.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
reshape.o: /usr/include/alloca.h /usr/include/assert.h reshape.h input.h
compass.o: /usr/include/stdlib.h /usr/include/features.h
compass.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
compass.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
compass.o: /usr/include/gnu/stubs-32.h /usr/include/sys/types.h
compass.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
compass.o: /usr/include/time.h /usr/include/endian.h
compass.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
compass.o: /usr/include/sys/select.h /usr/include/bits/select.h
compass.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
compass.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
compass.o: /usr/include/alloca.h /usr/include/assert.h /usr/include/GL/glut.h
compass.o: /usr/include/GL/freeglut_std.h /usr/include/GL/gl.h
compass.o: /usr/include/GL/glext.h /usr/include/inttypes.h
compass.o: /usr/include/stdint.h /usr/include/bits/wchar.h
compass.o: /usr/include/GL/glu.h compass.h display.h input.h reshape.h
ppm.o: /usr/include/stdio.h /usr/include/features.h
ppm.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
ppm.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
ppm.o: /usr/include/gnu/stubs-32.h /usr/include/bits/types.h
ppm.o: /usr/include/bits/typesizes.h /usr/include/libio.h
ppm.o: /usr/include/_G_config.h /usr/include/wchar.h
ppm.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ppm.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
ppm.o: /usr/include/endian.h /usr/include/bits/endian.h
ppm.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
ppm.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
ppm.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
ppm.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
ppm.o: /usr/include/GL/glut.h /usr/include/GL/freeglut_std.h
ppm.o: /usr/include/GL/gl.h /usr/include/GL/glext.h /usr/include/inttypes.h
ppm.o: /usr/include/stdint.h /usr/include/bits/wchar.h /usr/include/GL/glu.h
ppm.o: ppm.h
gettime.o: /usr/include/sys/time.h /usr/include/features.h
gettime.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
gettime.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
gettime.o: /usr/include/gnu/stubs-32.h /usr/include/bits/types.h
gettime.o: /usr/include/bits/typesizes.h /usr/include/time.h
gettime.o: /usr/include/bits/time.h /usr/include/sys/select.h
gettime.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
gettime.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
gettime.o: /usr/include/bits/confname.h /usr/include/getopt.h
midi.o: /usr/include/stdlib.h /usr/include/features.h
midi.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
midi.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
midi.o: /usr/include/gnu/stubs-32.h /usr/include/sys/types.h
midi.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
midi.o: /usr/include/time.h /usr/include/endian.h /usr/include/bits/endian.h
midi.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
midi.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
midi.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
midi.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
midi.o: /usr/include/string.h /usr/include/xlocale.h midi.h
